import { t } from 'i18next';

export const languageData = [

    {
        locale: 'en',
        translation: {
            Create_Your_Free_Account: `Create Your Free Account`,
            Welcome_to_247PRO: "Welcome to 247PRO",
            Welcome_To: "Welcome to",
            Please_provide_your_login_information: "Please provide your login information",
            Full_name: "Full name",
            Email: "Email",
            Next: "Next",
            Password: "Password",
            Login: `Login Your Account`,
            logintText: "Login",
            verifyBuisnessHeader: 'Help us to improve your experience by answering a few questions',
            Are_you_a_business: 'Are you a business?',
            yes: 'Yes',
            no: 'No',
            completeQuestions: `Complete these questions to receive job leads.`,
            Industry: "Industry",
            primarySpecialty: "Primary specialty",
            JobType: "Job type",
            ZipCode: "Zip code",
            MobilePhone: "Mobile phone",
            CompleteRegisration: "Complete Regisration",
            Verify: "Verify",
            RESEND_CODE: "RESEND CODE",
            resentText: "If you didn’t receive the code. Please click the button below.",
            enter_Code_Text: 'Enter 4 digit code sent to your mobile +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verify Your Mobile",
            Forget_your_password: "Forget your password?",
            resetInfoMsg: "To reset your password please provide the information below.",
            Reset_Password: "Reset Password",
            Email_or_phone: "Email or phone",
            Remember_you_password: "Remember you password?",
            Get_your_code: "Get your code",
            Verify_Proceed: "Verify & Proceed",
            Code_has_been_sent_to_your_phone_number: 'Code has been sent to your phone number.',
            Code_has_been_sent_to_your_EmailAddress: 'Code has been sent to your email address.',
            Set_your_password: "Set your password.",

            newPassMsg: `Your new password must be different from your previous password used`,
            New_password: "New password",
            Confirm_password: "Confirm password",
            Continue: "Continue",
            Phone_or_email: "Phone or email",
            Forget_Password: 'Forget Password',
            Remember_me: "Remember me",
            Continue_with_google: "Continue with google",
            Continue_with_Apple: "Continue with Apple",
            New_here: "New here? ",
            Create_an_free_account: "Create an free account ",
            or: "or",
            Whats_your_mobile_number: "What’s your mobile number?",
            Enter_Your_Email: "Enter Your Email",
            Mobile_phone_number: "Mobile phone number",
            AgreeTo: `By signing up, I agree to 247Pro’s`,
            TermsAndConditions: "Terms & Conditions.",
            Already_have_an_account: 'Already have an account? ',
            Marketplace: "Marketplace",
            SearchJobs: "Search jobs",
            UsemyProFindersavedleadpreferences: "Use my Pro Finder saved lead preferences",
            AdHocPreferences: "Ad-Hoc Preferences",
            RESET: "RESET",
            Jobtype: "Job type",
            Specialty: "Specialty",
            Location: 'Location',
            ApplyFilter: "Apply Filter",
            Majorrennovationforasinglefamilyhome: "Major rennovation for a single family home",
            marketPlaceMsg: "Hello all, I am looking for a contractor for my kitchen, I am looking for someone who can do my kitchen Thank you.",
            BurlingameCA: "Burlingame, CA",
            Cancel: "Cancel",
            Done: "Done",
            Construction: "Construction",
            Marketing: `Marketing`,
            Sales: "Sales",
            Software: "Software",
            All: "All",
            Plumbing: "Plumbing",
            Electrical: "Electrical",
            KitchenSink: "Kitchen sink",
            InstallAfaucet: "Install a faucet",
            InstallAsink: "Install a sink",
            InstallAtoilet: "Install a toilet",
            Tub: "Tub",
            WaterHeater: 'Water heater',
            Cities: "Cities",
            RadiussearchlimitedtotheUnitedStates: "Radius search limited to the United States",
            Searchorcreatenewcity: "Search or create new city",
            Radius: "Radius",
            PostaJob: "Post a Job",
            LeadPreference: "Lead Preference",
            MyFavorJobs: "My Favor Jobs",
            JobDescription: "Job Description",
            JobDescriptionMsg: "I like to do a whole house renovation, including one kitchen I like to do a whole house renovation, including one kitchen like to do a whole house renovation, including one one one one one one one one ",
            Attachments: "Attachments",
            ACCEPTTOBID: "ACCEPT TO BID",
            Congratulationsandgoodluckonyourbidding: "Congratulations and good luck on your bidding.",
            Createbidlater: "Create bid later",
            Setmatchingcriteriasforjobopportunities: "Set matching criterias for job opportunities",
            Theindustriesyouwillreceivejobleadsfrom: "The industries you will receive job leads from",
            IndustryPreferences: "Industry Preferences",
            CREATEABCINDUSTRY: "CREATE “ABC” INDUSTRY",
            Norecordfound: "No record found",
            BusinessCard: "Business Card",
            AddNewCart: "Add New Cart",
            Delete: "Delete",
            Edit: "Edit",
            Share: "Share",
            Copycardlink: "Copy card link",
            SaveQRtoPhotos: "Save QR to Photos",
            ShareQRviaEmail: "Share QR via Email",
            Shareanotherway: "Share another way",
            ShareCardviaText: "Share Card via Text",
            ShareCard: "Share Card",
            SaveContact: "Save Contact",
            Contactissavedtoandyour: "Contact is saved to 247PRO and your",
            CreateYourFreeBusinessCard: "Create Your Free Business Card",
            phoneContacts: "phone Contacts",
            alreadysavedinyourcontacts: "already saved in your contacts",
            NewBusinessCard: "New Business Card",
            firstname: "First name",
            lastName: "Last name",
            about: "about",
            About: "About",
            EMail: "E-mail",
            ContactInfo: 'Contact Info',
            Website: 'Website',
            StreetAddress: "Street address",
            AddCustomField: "Add Custom Field",
            SocialProfile: "Social Profile",
            AddSocialAccount: "Add Social Account",
            GreenMetroInc: "Green Metro Inc",
            Invite: "Invite",
            ApplicationsOrder: "Applications Order",
            Applications: "Applications",
            hideshow: "(hide/show)",
            BizCards: 'Biz Cards',
            BizCard: 'Biz Card',
            Calendar: "Calendar",
            Contacts: "Contacts",
            Events: "Events",
            Timeclock: "Timeclock",
            Members: "Members",
            Tasks: "Tasks",
            AccountAndSettings: "Account & Settings",
            CompanyProfile: 'Company Profile',
            AccountSettings: "Account Settings",
            ApplicaionSettings: "Applicaion Settings",
            Youhavenocontact: "You have no contact",
            search: "search",
            Company: "Company (200)",
            AddContact: "Add Contact",
            ConnectionRequests: "Connection Requests",
            Contacttype: "Contact type",
            NewContact: "New Contact",
            Companyname: "Company name",
            Speciality: 'Speciality',
            jobTitle: 'Job title',
            Websiteurl: "Website url",
            SHOWMORE: "SHOW MORE",
            Country: "Country",
            country: "country",
            StreetAddressLine2: "Street address line 2",
            City: "City",
            State: "State",
            PObox: "PO box",
            Label: "Label",
            Linktocompany: "Link to company",
            SelectAcompany: "Select a company",
            Attachment: "Attachment",
            SHOWLESS: "SHOW LESS",
            AddCompany: "Add Company",
            NewCompany: "New Company",
            Contactperson: "Contact person",
            Notes: "Notes",
            Entitytype: "Entity type",
            Staff: "Staff",
            Revenue: "Revenue",
            Address: "Address",
            Title: "Title",
            Capturenew: "Capture new",
            Uploadfromgallery: "Upload from gallery",
            mile: "mile",
            FilterCompany: "Filter Company",
            ClearFilters: "Clear Filters",
            Import: "Import",
            company: "Company",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "Allow 247pro to access photos, media and files on your device.",
            Deny: "Deny",
            Allow: "Allow",
            Files: "Files",
            Client: "Client",
            Emailaddress: "Email address",
            Nocompanylinked: "No company linked",
            NoCompanyName: "No Company Name",
            Generalcontractor: "General contractor",
            FromGreenMetroInc: "From Green Metro Inc.",
            Overview: "Overview",
            QRCode: "QR Code",
            Services: 'Services',
            Photos: "Photos",
            Reviews: "Reviews",
            Kitchenremodel: "Kitchen remodel",
            Bathroomremodel: "Bathroom remodel",
            AdditionsKitchenremodel: "Additions Kitchen remodel",
            Painting: "Painting",
            Electricalworks: "Electrical works",
            Painter: "Painter",
            Electrician: 'Electrician',
            twentyFiveReviews: "25 Reviews",
            ayearago: "a year ago",
            CopyQrCode: 'Copy Qr Code',
            CompanyQRCode: "Company QR Code",
            EditCompanyProfile: "Edit Company Profile",
            Companylogo: 'Company logo',
            Jobtypepreferences: "Job type preferences",
            Residential: "Residential",
            Commercial: "Commercial",
            ResidentialandCommercial: "Residential and Commercial",
            Addressline1: "Address line 1",
            Addressline2: "Address line 2",
            License: "License",
            Insurance: 'Insurance',
            Numberofstaff: "Number of staff",
            Annualrevenue: "Annual revenue",
            CFBond: "CF - Bond",
            SaveField: "Save Field",
            Entercustomfieldlabel: 'Enter custom field label',
            AddSpeciality: 'Add Speciality',
            selected: "selected",
            CreateNew: "Create New",
            windows: "windows",
            Plumber: "Plumber",
            Flooring: "Flooring",
            Architect: "Architect",
            AddNewSpecialty: "Add New Specialty",
            SaveChanges: "Save Changes",
            Nodatafound: 'No data found',
            Create: "Create",
            asnewspecialty: "as new specialty",
            AddNewService: "Add New Service",
            Upload: "Upload",
            filefromyourdevice: "file from your device",
            Maximum5fileseachupload: "(Maximum 5 files each upload)",
            DocumentCenter: "Document Center",
            Pickfrom: "Pick from ",
            Toaccessthisfeaturepleasevisitthewebinterface: "To access this feature, please visit the web interface!",
            UserAdmin: "User Admin",
            RolesAndPermissions: "Roles & Permissions",
            AccountInformation: "Account Information",
            ChangePassword: `Change Password`,
            Subscription: "Subscription",
            CountryAndLanguage: "Country & Language",
            CreateyourDigitalbusinesscard: "Create your Digital business card",
            Loginwithpassword: 'Login with password',
            LoginwithTouchID: "Login with Touch ID",
            LoginwithFaceID: "Login with Face ID",
            LoginInformation: 'Login Information',
            AccountType: "Account Type",
            PhoneNumber: "Phone Number",
            PrimarySpeciality: "Primary Speciality",
            Business: "Business",
            qrDexcription: "Your QR code is private. If you share it with someone, then can scan it with their 247Pro camera to add you as a contact.",
            GeorgeLee: "George Lee",
            ID: "ID",
            RequestConnect: "Request Connect",
            changePassMsg: "Your new password must be different from your previous password used.",
            Oldpassword: "Old password",

            Confirmnewpasword: "Confirm new pasword",
            UnitedStates: "United States",
            Language: "Language",
            English: "English",
            SelectLanguage: 'Select Language',
            SelectRegion: "Select Region",
            ProFinder: "Pro Finder",
            Basic: "Basic",
            MONTHLY: "MONTHLY",
            YEARLY50off: "YEARLY (50% off)",
            Upgrade: "Upgrade",
            ChangeimmediatelyCancelanytime: "Change immediately. Cancel anytime",
            Limitedtomathpermonth: "Limited to 1 math per month",
            FreelyenjoyourbasicProFinderfeatureslikejobpostingandjobmatches: "Freely enjoy our basic Pro Finder features like job posting and job matches.",
            Uptomatchespermonth: "Up to 5 matches per month",
            Forcompaniesthatneedtogrowtheirbusinessbutnotveryhungryfornewbusiness: "For companies that need to grow their business but not very hungry for new business",
            UserLicenses: "User Licenses",
            Setthenumberoflicensesfortheapplicationsorservices: "Set the number of licenses for the applications or services.",
            Areyousureyourwanttocancelyourcurrentsubscriptionplan: "Are you sure your want to cancel your current subscription plan?",
            CancelSubscription: "Cancel Subscription",
            Cancelnow: "Cancel now",
            CongratulationsYouhavesuccessfullyactivatedthesubscriptionforProFinderProaddonfeature: "Congratulations! You have successfully activated the subscription for Pro Finder Pro add-on feature.",
            SubscriptionActivated: 'Subscription Activated',
            CurrentSubscription: "Current Subscription",
            Permonthbilledyearly: "Per month, billed yearly",
            ProFinderPriority: "Pro Finder - Priority",
            Receivejobleadsinyourareas: "Receive job leads in your areas",
            Renewon: "Renew on:",
            EditSubscription: "Edit Subscription",
            SubscribedApplication: "Subscribed Application",
            AvailableApplications: "Available Applications",
            Invitepeopletojoinyourteam: 'Invite people to join your team',
            ShareaLink: "Share a Link",
            InvitewithContacts: 'Invite with Contacts',
            ScanMyQRCode: "Scan My QR Code",
            Whatsyourphoneoremail: "Whats your phone or email?",
            Continue_with_Email: "Continue with email",
            Verify_Your_Email: "Verify Your Email",
            emailVerifyMsg: 'Enter 4 digit code sent to your email (johndoe@gmail.com)',
            VerifyLater: "Verify Later",
            Status: "Status",
            Open: "Open",
            Closed: "Closed",
            Confirm: 'Confirm',
            Searchpostedjobs: "Search posted jobs",
            Kitchenremodelforasinglefamilyhome: "Kitchen remodel for a single family home...",
            Bidders: "Bidders:  ",
            Bids: "Bids:  ",
            View: "View",
            Converttoproject: "Convert to project",
            ChangeStatus: "Change Status",
            EditJob: "Edit Job",
            HourlyRate: 'Hourly Rate',
            Amount: 'Amount',
            Attachmentsoptional: "Attachments (optional)",
            FindlocalprosandgetbidsforKitchenRemodelforsinglefamilyhome: "Find local pros and get bids for Kitchen Remodel for single family home",
            Description: "Description",
            Duedate: "Due date",

            Budget: "Budget",
            FixedBudget: "Fixed Budget",
            Enterstreetaddressline2: 'Enter street address line 2',
            Kitchenremodelforasingle: "Kitchen remodel for a single...",
            Hire: "Hire",
            Reject: "Reject",
            JobInfo: "Job Info",
            viewJobDescription: "I like to do a whole house renovation, including one kitchen I like to do a whole house renovation, including one kitchen like to do a whole house renovation, in...",
            BiddersAndBids: "Bidders & Bids",
            Nobidderyet: "No bidder yet ",
            BidderLee: "Bidder Lee",
            Invited: "Invited",
            ETA: 'ETA',
            Cost: "Cost",
            Inviteprostobid: "Invite pros to bid",
            Phone:"Phone",
            Createdby:"Created by",
            Date:"Date",
            Biddescription:"Bid description",
        }
    },
    {
        locale: 'ch',
        translation: {
            Create_Your_Free_Account: `创建您的免费帐户`,
            Please_provide_your_login_information: "请提供您的登录信息",
            Full_name: "全名",
            verifyBuisnessHeader: '回答几个问题帮助我们改善您的体验',
            Are_you_a_business: '你是企业吗？',
            Email: "电子邮件",
            Next: "下一步",
            Password: "密码",
            Welcome_to_247PRO: "欢迎来到247PRO",
            Login: `登录您的帐户`,
            yes: '是的',
            no: '不',
            completeQuestions: `完成这些问题以获得工作机会。`,
            Industry: "行业",
            primarySpecialty: "主要专业",
            JobType: "工作类型",
            MobilePhone: "邮政编码",
            CompleteRegisration: "完成注册",
            Verify: "核实",
            ZipCode: "邮政编码",
            RESEND_CODE: "重新发送验证码",
            resentText: "如果您没有收到代码。 请点击下面的按钮。",
            enter_Code_Text: '输入发送至您手机 +1 (234) 567 8900 的 4 位数代码。',

            Verify_Your_Mobile: "验证您的手机",
            Forget_your_password: "忘记密码？",
            resetInfoMsg: "要重置您的密码，请提供以下信息。",
            Reset_Password: "重设密码",
            Email_or_phone: "邮件或者电话",

            Remember_you_password: "还记得你的密码吗？",
            logintText: "登录",
            Get_your_code: "获取您的代码",
            Code_has_been_sent_to_your_phone_number: '代码已发送至您的电话号码',
            Verify_Proceed: "验证并继续",
            Code_has_been_sent_to_your_EmailAddress: '代码已发送至您的电子邮件地址。',
            Set_your_password: "设置你的密码。",
            newPassMsg: `您的新密码必须与之前使用的密码不同。`,
            New_password: "新密码",
            Confirm_password: "确认密码",
            Continue: "继续",
            Phone_or_email: "电话还是邮件",

            Welcome_To: "欢迎来到",
            Forget_Password: '忘记密码',
            Remember_me: "记住账号",
            Continue_with_google: "继续使用谷歌",
            Continue_with_Apple: "继续使用苹果",

            New_here: "新来的？",
            Create_an_free_account: "创建一个免费帐户",
            or: "或者",
            Whats_your_mobile_number: "你手机号码多少？",
            Enter_Your_Email: "输入你的电子邮箱",

            Mobile_phone_number: "手机号码",
            AgreeTo: `注册即表示我同意 247Pro 的`,
            TermsAndConditions: "条款和条件。",
            Already_have_an_account: '已经有帐户？',
            Marketplace: "市场",
            SearchJobs: "搜索职位",
            UsemyProFindersavedleadpreferences: "使用我的 Pro Finder 保存的潜在客户首选项",
            AdHocPreferences: "临时首选项",
            RESET: "重置",
            Jobtype: "工作类型",
            Specialty: "专业",
            Location: '地点',
            ApplyFilter: "应用过滤器",
            Majorrennovationforasinglefamilyhome: "单一家庭住宅的重大翻新",
            marketPlaceMsg: "大家好，我正在寻找一个厨房承包商，我正在寻找可以做我的厨房的人，谢谢。",
            BurlingameCA: "加利福尼亚州伯林格姆",
            Cancel: "取消",
            Done: "完毕",
            Construction: "建造",
            Marketing: `营销`,
            Sales: "销售量",
            Software: "软件",
            All: "全部",
            Plumbing: "水暖",
            Electrical: "电气",
            KitchenSink: "厨房水槽",
            InstallAfaucet: "安装水龙头",
            InstallAsink: "安装水槽",
            InstallAtoilet: "安装厕所",
            Tub: "浴缸",
            WaterHeater: '热水器',
            Cities: "城市",
            RadiussearchlimitedtotheUnitedStates: "半径搜索仅限于美国",
            Searchorcreatenewcity: "搜索或创建新城市",
            Radius: "半径",
            PostaJob: "发布职位",
            LeadPreference: "潜在客户偏好",
            MyFavorJobs: "我最喜欢的工作",
            JobDescription: "职位描述",
            JobDescriptionMsg: "我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一一一一一一一一",
            BizCards: '名片',
            Calendar: "日历",
            Tasks: "任务",

            Attachments: "附件",
            ACCEPTTOBID: "接受投标",
            Congratulationsandgoodluckonyourbidding: "恭喜您并祝您投标顺利。",
            Createbidlater: "稍后创建出价",
            Setmatchingcriteriasforjobopportunities: "设定工作机会的匹配标准",
            Theindustriesyouwillreceivejobleadsfrom: "您将收到工作机会的行业",
            IndustryPreferences: "行业偏好",
            Norecordfound: "行业偏好",
            CREATEABCINDUSTRY: "打造“ABC”产业",
            BusinessCard: "名片",
            AddNewCart: "添加新购物车",
            Delete: "删除",
            Share: "分享",
            Edit: "编辑",
            Copycardlink: "复制卡链接",
            SaveQRtoPhotos: "将二维码保存到照片",
            ShareQRviaEmail: "通过电子邮件分享二维码",
            Shareanotherway: "分享另一种方式",
            ShareCardviaText: "通过短信分享卡",
            ShareCard: "共享卡",
            SaveContact: "保存联系方式",
            CreateYourFreeBusinessCard: "创建您的免费名片",
            Contactissavedtoandyour: "联系人信息将保存至 247PRO，并且您的",
            phoneContacts: "电话 联系方式",
            alreadysavedinyourcontacts: "已保存在您的通讯录中",
            NewBusinessCard: "新名片",
            firstname: "名",
            lastName: "姓",
            about: "关于",
            About: "关于",
            EMail: "电子邮件",
            ContactInfo: '联系方式',
            Website: '网站',
            StreetAddress: "街道地址",
            AddCustomField: "添加自定义字段",
            SocialProfile: "社会概况",
            AddSocialAccount: "添加社交帐户",
            GreenMetroInc: "绿色地铁公司",
            Invite: "邀请",
            ApplicationsOrder: "申请订单",
            Applications: "应用领域",
            hideshow: "（隐藏/显示）",
            Contacts: "联系方式",
            Events: "活动",
            Timeclock: "时钟",
            Members: "会员",
            AccountAndSettings: "帐号设定",
            CompanyProfile: '公司简介',
            AccountSettings: "帐号设定",
            BizCard: '名片卡',
            ApplicaionSettings: "应用程序设置",
            Youhavenocontact: "你没有联系方式",
            search: "搜索",
            Company: "公司 (200)",
            AddContact: "增加联系人",
            ConnectionRequests: "连接请求",
            NewContact: "新联系人",
            Contacttype: "触点类型",
            Companyname: "公司名称",
            Speciality: '专业',
            jobTitle: '职称',
            Websiteurl: "网址",
            SHOWMORE: "展示更多",
            country: "国家",
            StreetAddressLine2: "街道地址第 2 行",
            City: "城市",
            State: "状态",
            PObox: "邮政信箱",
            Label: "标签",
            Linktocompany: "链接至公司",
            SelectAcompany: "选择公司",
            Attachment: "依恋",
            SHOWLESS: "显示较少",
            AddCompany: "添加公司",
            NewCompany: "新公司",
            Contactperson: "联络人",
            Entitytype: "实体类型",
            Staff: "职员",

            Notes: "笔记",
            Revenue: "收入",
            Address: "地址",
            Title: "标题",
            Capturenew: "捕捉新的",
            Uploadfromgallery: "从图库上传",
            mile: "英里",
            ClearFilters: "清除过滤器",
            FilterCompany: "过滤器公司",
            company: "公司",
            Import: "进口",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "允许 247pro 访问您设备上的照片、媒体和文件。",
            Deny: "否定",
            Allow: "允许",
            Files: "文件",
            Client: "客户",
            Emailaddress: "电子邮件地址",
            Nocompanylinked: "没有公司LinkedIn",
            NoCompanyName: "无公司名称",
            Generalcontractor: "总承包人",
            FromGreenMetroInc: "来自绿色地铁公司",
            QRCode: "二维码",
            Overview: "概述",
            Services: '服务',
            Photos: "相片",
            Reviews: "评论",
            Kitchenremodel: "厨房改造",
            Bathroomremodel: "浴室改造",
            AdditionsKitchenremodel: "厨房改造加建",
            Painting: "绘画",
            Electricalworks: "电力工程",
            Electrician: '电工',
            Painter: "画家",
            twentyFiveReviews: "25 条评论",
            ayearago: "一年前",
            CopyQrCode: '复制二维码',
            CompanyQRCode: "公司二维码",
            EditCompanyProfile: "编辑公司简介",
            Companylogo: '公司标志',
            Jobtypepreferences: "工作类型偏好",
            Residential: "住宅",
            Commercial: "商业的",
            ResidentialandCommercial: "住宅及商业",
            Addressline1: "地址第一行",
            Addressline2: "地址行2",
            License: "执照",
            Insurance: '保险',
            Numberofstaff: "员工人数",
            Annualrevenue: "年收入",
            CFBond: "CF-债券",
            SaveField: "保存字段",
            Entercustomfieldlabel: '输入自定义字段标签',
            AddSpeciality: '添加专业',
            selected: "已选择",
            CreateNew: "创建新的",
            windows: "视窗",
            Plumber: "水管工",
            Flooring: "地板",
            Architect: "建筑师",
            AddNewSpecialty: "添加新专业",
            SaveChanges: "保存更改",
            Nodatafound: '没有找到数据',
            Create: "创造",
            asnewspecialty: "作为新专业",
            AddNewService: "添加新服务",
            Upload: "上传",
            filefromyourdevice: "来自您设备的文件",
            Maximum5fileseachupload: "（每次最多上传5个文件）",
            DocumentCenter: "文档中心",
            Pickfrom: "从中挑选",
            Toaccessthisfeaturepleasevisitthewebinterface: "要访问此功能，请访问网络界面！",
            UserAdmin: "用户管理",
            RolesAndPermissions: "角色和权限",
            AccountInformation: "帐户信息",
            ChangePassword: `更改密码`,
            Subscription: "订阅",
            CountryAndLanguage: "国家和语言",
            CreateyourDigitalbusinesscard: "创建您的数字名片",
            Loginwithpassword: '使用密码登录',
            LoginwithFaceID: "使用面容 ID 登录",
            LoginwithTouchID: "使用 Touch ID 登录",
            LoginInformation: '登录信息',
            PrimarySpeciality: "主要专业",
            PhoneNumber: "电话号码",
            AccountType: "帐户类型",
            Business: "商业",
            qrDexcription: "您的二维码是私人的。 如果您与某人共享，则可以使用他们的 247Pro 相机扫描它以将您添加为联系人。",
            GeorgeLee: "乔治·李",
            ID: "ID",
            RequestConnect: "请求连接",
            changePassMsg: "您的新密码必须与之前使用的密码不同。",
            Oldpassword: "旧密码",
            Confirmnewpasword: "确认新密码",
            Country: "国家",
            UnitedStates: "美国",
            Language: "语言",
            English: "英语",
            SelectLanguage: '选择语言',
            SelectRegion: "选择地区",
            ProFinder: "专业查找器",
            Basic: "基本的",
            MONTHLY: "每月",
            YEARLY50off: "每年（50% 折扣）",
            Upgrade: "升级",
            ChangeimmediatelyCancelanytime: "立即改变。 随时取消",
            Limitedtomathpermonth: "每月仅限 1 门数学课",
            FreelyenjoyourbasicProFinderfeatureslikejobpostingandjobmatches: "免费享受我们的基本 Pro Finder 功能，例如职位发布和职位匹配。",
            Uptomatchespermonth: "每月最多 5 场比赛",
            Forcompaniesthatneedtogrowtheirbusinessbutnotveryhungryfornewbusiness: "对于需要发展业务但不太渴望新业务的公司",
            UserLicenses: "用户许可证",
            Setthenumberoflicensesfortheapplicationsorservices: "设置应用程序或服务的许可证数量。",
            Areyousureyourwanttocancelyourcurrentsubscriptionplan: "您确定要取消当前的订阅计划吗？",
            CancelSubscription: "取消订阅",
            Cancelnow: "立即取消",
            CongratulationsYouhavesuccessfullyactivatedthesubscriptionforProFinderProaddonfeature: "恭喜！ 您已成功激活 Pro Finder Pro 附加功能的订阅。",
            SubscriptionActivated: '订阅已激活',
            CurrentSubscription: "当前订阅",
            Permonthbilledyearly: "按月、按年计费",
            ProFinderPriority: "专业查找器 - 优先",
            Receivejobleadsinyourareas: "接收您所在地区的工作机会",
            Renewon: "续订日期：",
            EditSubscription: "编辑订阅",
            SubscribedApplication: "订阅的应用程序",
            AvailableApplications: "可用的应用程序",
            Invitepeopletojoinyourteam: '邀请人们加入您的团队',
            ShareaLink: "分享链接",
            InvitewithContacts: '邀请联系人',
            ScanMyQRCode: "扫描我的二维码",
            Whatsyourphoneoremail: "您的电话或电子邮件是什么？",
            Continue_with_Email: "继续使用电子邮件",
            Verify_Your_Email: "验证您的电子邮件",
            emailVerifyMsg: '输入发送到您的电子邮件 (johndoe@gmail.com) 的 4 位数代码',
            VerifyLater: "稍后验证",
            Status: "地位",
            Open: "打开",
            Closed: "关闭",
            Confirm: '确认',
            Searchpostedjobs: "搜索发布的职位",
            Kitchenremodelforasinglefamilyhome: "单身家庭的厨房改造...",
            Bidders: "投标人：",
            Bids: "出价：",
            View: "看法",
            Converttoproject: "转换为项目",
            ChangeStatus: "更改状态",
            EditJob: "编辑职位",
            HourlyRate: '每小时收费',
            Amount: '数量',
            Attachmentsoptional: "附件（可选）",
            FindlocalprosandgetbidsforKitchenRemodelforsinglefamilyhome: "寻找当地专业人士并获得单户住宅厨房改造的投标",
            Description: "描述",
            Duedate: "到期日",
            Budget: "预算",
            FixedBudget: "固定预算",
            Enterstreetaddressline2: '输入街道地址第 2 行',
            Kitchenremodelforasingle: "单身人士的厨房改造...",
            Hire: "聘请",
            Reject: "拒绝",
            JobInfo: "职位信息",
            viewJobDescription: "我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一间厨房喜欢做全屋装修，在...",
            BiddersAndBids: "投标人及投标",
            Nobidderyet: "还没有投标人 ",
            BidderLee: "李竞标者",
            Invited: "受邀",
            ETA: '预计到达时间',
            Cost: "成本",
            Inviteprostobid: "邀请专业人士投标",
            Phone:"电话",
            Createdby:"由...制作",
            Date:"日期",
            Biddescription:"投标说明",


        }
    },
    {
        locale: 'es',
        translation: {
            Create_Your_Free_Account: `Crea tu cuenta gratuita`,
            Welcome_to_247PRO: "Bienvenido a 247PRO",
            Please_provide_your_login_information: "Por favor proporcione su información de inicio de sesión",
            Login: `inicie sesión en su cuenta`,
            Password: "Contraseña",
            verifyBuisnessHeader: 'Ayúdanos a mejorar tu experiencia respondiendo algunas preguntas',
            Next: "Siguiente",
            Full_name: "Nombre completo",
            Email: "Correo electrónico",
            Are_you_a_business: '¿Eres un negocio?',
            yes: 'Sí',
            no: 'No',
            completeQuestions: `Complete estas preguntas para recibir oportunidades de trabajo.`,
            Industry: "Industria",
            primarySpecialty: "especialidad primaria",
            JobType: "El tipo de trabajo",
            ZipCode: "Código postal",
            MobilePhone: "Código postal",
            CompleteRegisration: "Registro completo",
            Verify: "Verificar",
            RESEND_CODE: "REENVIAR CODIGO",
            resentText: "Si no recibiste el código. Por favor, haga clic en el botón de abajo.",
            enter_Code_Text: 'Ingresa el código de 4 dígitos enviado a tu móvil +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verifica tu móvil",
            Forget_your_password: "¿Olvidaste tu contraseña?",
            resetInfoMsg: "Para restablecer su contraseña, proporcione la información a continuación.",
            Reset_Password: "Restablecer la contraseña",
            Email_or_phone: "Email o teléfono",
            Remember_you_password: "¿Recuerdas tu contraseña?",
            logintText: "Acceso",
            Get_your_code: "Consigue tu código",
            Code_has_been_sent_to_your_phone_number: 'El código ha sido enviado a su número de teléfono',
            Verify_Proceed: "Verificar y continuar",
            Code_has_been_sent_to_your_EmailAddress: 'El código ha sido enviado a su dirección de correo electrónico.',
            newPassMsg: `Su nueva contraseña debe ser diferente de su contraseña anterior utilizada.`,
            Set_your_password: "Establece tu contraseña.",
            New_password: "Nueva contraseña",
            Confirm_password: "Confirmar Contraseña",
            Continue: "Continuar",
            Phone_or_email: "Teléfono o correo electrónico",
            Welcome_To: "Bienvenida a",
            Forget_Password: 'Contraseña olvidada',

            Remember_me: "Acuérdate de mí",
            Continue_with_google: "continuar con google",
            Continue_with_Apple: "Continuar con Apple",
            Create_an_free_account: "Crea una cuenta gratis",
            New_here: "Nueva aquí?",
            or: "o",
            Whats_your_mobile_number: "¿Cual es tu numero de móvil?",
            Mobile_phone_number: "Número de teléfono móvil",
            Enter_Your_Email: "Introduce tu correo electrónico",
            AgreeTo: `Al registrarme, acepto las condiciones de 247Pro`,
            TermsAndConditions: "Términos y condiciones.",
            Already_have_an_account: '¿Ya tienes una cuenta? ',
            Marketplace: "Mercado",
            SearchJobs: "Buscar empleos",
            UsemyProFindersavedleadpreferences: "Usar mis preferencias de clientes potenciales guardadas en Pro Finder",
            AdHocPreferences: "Preferencias ad hoc",
            RESET: "REINICIAR",
            Jobtype: "El tipo de trabajo",
            Specialty: "Especialidad",
            Location: 'Ubicación',
            ApplyFilter: "Aplicar filtro",
            Majorrennovationforasinglefamilyhome: "Renovación importante para una vivienda unifamiliar.",
            marketPlaceMsg: "Hola a todos, estoy buscando un contratista para mi cocina, estoy buscando alguien que pueda hacer mi cocina. Gracias.",
            BurlingameCA: "Burlingame, California, EE.UU.",
            Cancel: "Cancelar",
            Construction: "Construcción",
            Done: "Hecho",
            Marketing: `Marketing`,
            Sales: "Ventas",
            Software: "Software",
            All: "Toda",
            Plumbing: "Plomería",
            Electrical: "Eléctrica",
            KitchenSink: "Fregadero",
            InstallAfaucet: "instalar un grifo",
            InstallAsink: "instalar un fregadero",
            InstallAtoilet: "instalar un baño",
            Tub: "Bañera",
            WaterHeater: 'Calentador de agua',
            Cities: "Ciudades",
            RadiussearchlimitedtotheUnitedStates: "Búsqueda de radio limitada a los Estados Unidos",
            Searchorcreatenewcity: "Buscar o crear una nueva ciudad",
            PostaJob: "Anunciar un trabajo",
            Radius: "Radio",
            LeadPreference: "Preferencia de cliente potencial",
            MyFavorJobs: "Mis trabajos favoritos",
            JobDescription: "Descripción del trabajo",
            JobDescriptionMsg: "Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una uno uno uno uno uno uno uno",
            Attachments: "Archivos adjuntos",
            ACCEPTTOBID: "ACEPTAR OFERTA",
            Congratulationsandgoodluckonyourbidding: "Felicitaciones y buena suerte con su oferta.",
            Createbidlater: "Crear oferta más tarde",
            Setmatchingcriteriasforjobopportunities: "Establecer criterios coincidentes para las oportunidades laborales",
            Theindustriesyouwillreceivejobleadsfrom: "Las industrias de las que recibirá oportunidades de empleo",
            IndustryPreferences: "Preferencias de la industria",
            Norecordfound: "Preferencias de la industria",
            CREATEABCINDUSTRY: "CREAR LA INDUSTRIA “ABC”",
            BusinessCard: "Tarjeta de visita",
            AddNewCart: "Agregar nuevo carrito",
            Delete: "Borrar",
            Share: "Compartir",
            Edit: "Editar",
            Copycardlink: "Copiar enlace de tarjeta",
            SaveQRtoPhotos: "Guardar QR en fotos",
            ShareQRviaEmail: "Compartir QR por correo electrónico",
            Shareanotherway: "Comparte de otra manera",
            ShareCardviaText: "Compartir tarjeta por mensaje de texto",
            ShareCard: "Compartir tarjeta",
            SaveContact: "Guardar contacto",
            CreateYourFreeBusinessCard: "Crea tu tarjeta de presentación gratuita",
            Contactissavedtoandyour: "El contacto se guarda en 247PRO y su",
            phoneContacts: "Contactos telefonicas",
            alreadysavedinyourcontacts: "ya guardado en tus contactos",
            Invite: "Invitar",
            NewBusinessCard: "Nueva tarjeta de presentación",
            firstname: "Nombre de pila",
            lastName: "Apellido",
            about: "acerca de",
            About: "Acerca de",
            EMail: "Correo electrónico",
            ContactInfo: 'Datos de contacto',
            Website: 'Sitio web',
            StreetAddress: "Dirección",
            AddCustomField: "Agregar campo personalizado",
            SocialProfile: "Perfil social",
            AddSocialAccount: "Agregar cuenta social",
            GreenMetroInc: "Metro Verde Inc.",
            ApplicationsOrder: "Orden de aplicaciones",
            Applications: "Aplicaciones",
            hideshow: "(ocultar mostrar)",
            BizCards: 'Tarjetas de visita',
            Calendar: "Calendario",
            Contacts: "Contactos",
            Events: "Eventos",
            Timeclock: "reloj de tiempo",
            Members: "Miembros",
            Tasks: "Tareas",
            AccountAndSettings: "Configuraciones de la cuenta",
            CompanyProfile: 'Perfil de la empresa',
            AccountSettings: "Configuraciones de la cuenta",
            BizCard: 'Tarjeta de visita',
            ApplicaionSettings: "Configuraciones de la aplicación",
            Youhavenocontact: "no tienes contacto",
            search: "buscar",
            Company: "Empresa (200)",
            AddContact: "Agregar contacto",
            ConnectionRequests: "Solicitudes de conexión",
            NewContact: "Nuevo contacto",
            Contacttype: "Tipo de Contacto",
            Companyname: "Nombre de empresa",
            Speciality: 'Especialidad',
            jobTitle: 'título profesional',
            Websiteurl: "URL del sitio web",
            SHOWMORE: "MOSTRAR MÁS",
            country: "país",
            StreetAddressLine2: "Dirección de calle Linea 2",
            City: "Ciudad",
            State: "Estado",
            PObox: "apartado postal",
            Label: "Etiqueta",
            Linktocompany: "Enlace a la empresa",
            SelectAcompany: "Seleccione una empresa",
            Attachment: "Adjunto",
            SHOWLESS: "MUESTRA MENOS",
            AddCompany: "Agregar empresa",
            NewCompany: "Nueva compañia",
            Contactperson: "Persona de contacto",
            Notes: "Notas",
            Entitytype: "Tipo de entidad",
            Staff: "Personal",
            Revenue: "Ganancia",
            Address: "DIRECCIÓN",
            Title: "Título",
            Capturenew: "Capturar nueva",
            Uploadfromgallery: "Subir desde la galería",
            mile: "milla",
            ClearFilters: "Borrar filtros",
            FilterCompany: "Filtrar empresa",
            company: "Compañía",
            Import: "Importar",
            Deny: "Denegar",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "Permita que 247pro acceda a fotos, medios y archivos en su dispositivo.",
            Allow: "Permitir",
            Files: "Archivos",
            Client: "Cliente",
            Emailaddress: "Dirección de correo electrónico",
            Nocompanylinked: "Ninguna empresa linkedin",
            NoCompanyName: "Sin nombre de empresa",
            Generalcontractor: "Contratista general",
            FromGreenMetroInc: "De Green Metro Inc.",
            QRCode: "Código QR",
            Overview: "Descripción general",
            Services: 'Servicios',
            Photos: "Fotos",
            Reviews: "Reseñas",
            Kitchenremodel: "remodelación de cocina",
            Bathroomremodel: "remodelación del baño",
            AdditionsKitchenremodel: "Adiciones remodelación de cocina",
            Painting: "Cuadro",
            Electricalworks: "Obras eléctricas",
            Electrician: 'Electricista',
            Painter: "Pintora",
            twentyFiveReviews: "25 reseñas",
            ayearago: "Hace un año",
            CopyQrCode: 'Copiar código QR',
            CompanyQRCode: "Código QR de la empresa",
            EditCompanyProfile: "Editar perfil de empresa",
            Companylogo: 'Logo de la compañía',
            Jobtypepreferences: "Preferencias de tipo de trabajo",
            Residential: "Residencial",
            Commercial: "Comercial",
            ResidentialandCommercial: "Residencial y comercial",
            Addressline1: "Dirección Línea 1",
            Addressline2: "Línea de dirección 2",
            License: "Licencia",
            Insurance: 'Seguro',
            Numberofstaff: "Numero de empleado",
            Annualrevenue: "Ingresos anuales",
            CFBond: "CF - Bono",
            SaveField: "Guardar campo",
            Entercustomfieldlabel: 'Ingrese la etiqueta del campo personalizado',
            AddSpeciality: 'Agregar especialidad',
            selected: "seleccionada",
            CreateNew: "Crear nueva",
            windows: "ventanas",
            Plumber: "Plomero",
            Flooring: "Piso",
            Architect: "Arquitecta",
            AddNewSpecialty: "Agregar nueva especialidad",
            SaveChanges: "Guardar cambios",
            Nodatafound: 'Datos no encontrados',
            Create: "Crear",
            asnewspecialty: "como nueva especialidad",
            AddNewService: "Agregar nuevo servicio",
            Upload: "Subir",
            filefromyourdevice: "archivo desde su dispositivo",
            Maximum5fileseachupload: "(Máximo 5 archivos por carga)",
            DocumentCenter: "Centro de documentos",
            Pickfrom: "Escoge de",
            Toaccessthisfeaturepleasevisitthewebinterface: "Para acceder a esta función, visite la interfaz web!",
            UserAdmin: "Administrador de usuarios",
            RolesAndPermissions: "Roles y permisos",
            AccountInformation: "Información de la cuenta",
            ChangePassword: `Cambiar la contraseña`,
            Subscription: "Suscripción",
            CountryAndLanguage: "Lenguaje del pais",
            CreateyourDigitalbusinesscard: "Crea tu tarjeta de presentación digital",
            Loginwithpassword: 'Iniciar sesión con contraseña',
            LoginwithFaceID: "Iniciar sesión con Face ID",
            LoginwithTouchID: "Iniciar sesión con Touch ID",
            LoginInformation: 'Información Entrar',
            PrimarySpeciality: "Especialidad Primaria",
            AccountType: "Tipo de cuenta",
            PhoneNumber: "Número de teléfono",
            Business: "Negocio",
            qrDexcription: "Tu código QR es privado. Si lo compartes con alguien, podrás escanearlo con su cámara 247Pro para agregarte como contacto.",
            GeorgeLee: "jorge lee",
            ID: "IDENTIFICACIÓN",
            RequestConnect: "Solicitar conexión",
            changePassMsg: "Su nueva contraseña debe ser diferente de la contraseña utilizada anteriormente.",
            Oldpassword: "Contraseña anterior",
            Confirmnewpasword: "Confirmar nueva contraseña",
            Country: "País",
            UnitedStates: "Estados Unidos",
            Language: "Idioma",
            English: "Inglesa",
            SelectLanguage: 'Seleccione el idioma',
            SelectRegion: "Seleccione región",
            ProFinder: "Buscador profesional",
            Basic: "Básica",
            MONTHLY: "MENSUAL",
            YEARLY50off: "ANUAL (50% de descuento)",
            Upgrade: "Mejora",
            ChangeimmediatelyCancelanytime: "Cambie inmediatamente. Cancelar en cualquier momento",
            Limitedtomathpermonth: "Limitado a 1 matemática por mes",
            FreelyenjoyourbasicProFinderfeatureslikejobpostingandjobmatches: "Disfrute libremente de nuestras funciones básicas de Pro Finder, como publicación de empleos y coincidencias de empleos.",
            Uptomatchespermonth: "Hasta 5 partidos por mes",
            Forcompaniesthatneedtogrowtheirbusinessbutnotveryhungryfornewbusiness: "Para empresas que necesitan hacer crecer su negocio pero no tienen mucha hambre de nuevos negocios",
            UserLicenses: "Licencias de usuario",
            Setthenumberoflicensesfortheapplicationsorservices: "Establecer el número de licencias para las aplicaciones o servicios.",
            Areyousureyourwanttocancelyourcurrentsubscriptionplan: "¿Está seguro de que desea cancelar su plan de suscripción actual?",
            CancelSubscription: "Cancelar suscripción",
            Cancelnow: "Cancelar ahora",
            CongratulationsYouhavesuccessfullyactivatedthesubscriptionforProFinderProaddonfeature: "¡Felicidades! Ha activado correctamente la suscripción a la función complementaria Pro Finder Pro.",
            SubscriptionActivated: 'Suscripción activada',
            CurrentSubscription: "Suscripción actual",
            Permonthbilledyearly: "Por mes, facturado anualmente",
            ProFinderPriority: "Buscador profesional: prioridad",
            Receivejobleadsinyourareas: "Recibe oportunidades de empleo en tus áreas",
            Renewon: "Renovar el:",
            EditSubscription: "Editar suscripción",
            SubscribedApplication: "Solicitud suscrita",
            AvailableApplications: "Aplicaciones disponibles",
            Invitepeopletojoinyourteam: 'Invita a personas a unirse a tu equipo',

            ShareaLink: "Compartir un enlace",
            InvitewithContacts: 'Invitar con contactos',
            ScanMyQRCode: "Escanea mi código QR",
            Whatsyourphoneoremail: "¿Cuál es tu teléfono o correo electrónico?",
            Continue_with_Email: "Continuar con el correo electrónico",
            Verify_Your_Email: "Verifica tu correo electrónico",
            emailVerifyMsg: 'Ingrese el código de 4 dígitos enviado a su correo electrónico (johndoe@gmail.com)',
            VerifyLater: "Verificar más tarde",
            Status: "Estado",
            Open: "Abierta",
            Closed: "Cerrada",
            Confirm: 'Confirmar',
            Searchpostedjobs: "Buscar trabajos publicados",
            Kitchenremodelforasinglefamilyhome: "Reforma de cocina para vivienda unifamiliar...",
            Bidders: "Postoras: ",
            Bids: "Ofertas:",
            View: "Vista",
            Converttoproject: "Convertir a proyecto",
            ChangeStatus: "Cambiar Estado",
            EditJob: "Editar trabajo",
            HourlyRate: 'Tarifa por hora',
            Amount: 'Cantidad',
            Attachmentsoptional: "Archivos adjuntos (opcional)",

            FindlocalprosandgetbidsforKitchenRemodelforsinglefamilyhome: "Encuentre profesionales locales y obtenga ofertas para remodelación de cocinas para viviendas unifamiliares",
            Description: "Descripción",
            Duedate: "Fecha de vencimiento",
            Budget: "Presupuesto",
            FixedBudget: "Presupuesto fijo",
            Enterstreetaddressline2: 'Ingrese la dirección de la calle en la línea 2',
            Kitchenremodelforasingle: "Reforma de cocina para una persona...",
            Hire: "Contratar",
            Reject: "Rechazar",
            JobInfo: "Información del trabajo",
            viewJobDescription: "Me gusta hacer una renovación completa de la casa, incluida una cocina. Me gusta hacer una renovación completa de la casa, incluida una cocina. Me gusta hacer una renovación completa de la casa, en...",
            BiddersAndBids: "Postores y ofertas",
            Nobidderyet: "Ningún postor todavía",
            BidderLee: "Postor Lee",
            Invited: "Invitada",
            ETA: 'ETA',
            Cost: "Costo",
            Inviteprostobid: "Invita a profesionales a pujar",
            Phone:"Teléfono",
            Createdby:"Creado por",
            Date:"Fecha",
            Biddescription:"Descripción de la oferta",
            
        }
    }
];

export type languageProps = {
    id: string;
    name: string;
    code: string;
};

export const appLanguages: languageProps[] = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'chinese',
        code: 'ch'
    },
    {
        id: '5',
        name: 'Spanish',
        code: 'es'
    }
];
